//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub use super::t_comment::Entity as TComment;
pub use super::t_idiom::Entity as TIdiom;
pub use super::t_poet::Entity as TPoet;
pub use super::t_poetry::Entity as TPoetry;
pub use super::t_saying::Entity as TSaying;
pub use super::t_tag::Entity as TTag;
pub use super::t_user::Entity as TUser;
