//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "t_comment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub contents: Option<String>,
    pub up: Option<i64>,
    pub parent_id: Option<i64>,
    pub creator_id: Option<i64>,
    pub creator_name: Option<i64>,
    pub creator_avatar: Option<i64>,
    pub publish_area: Option<String>,
    pub resource_id: Option<i64>,
    pub resource_type: Option<i64>,
    #[sea_orm(column_type = "Custom(\"inet\".to_owned())", nullable)]
    pub ip: Option<String>,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
