//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "t_idiom")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub word: String,
    pub pinyin: Option<String>,
    pub example: Option<String>,
    pub explanation: Option<String>,
    pub derivation: Option<String>,
    pub abbreviation: Option<String>,
    pub favorite: Option<i32>,
    pub create_time: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
