//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "t_poetry")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub author: String,
    pub author_id: Option<String>,
    pub style: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub contents: Option<String>,
    pub rhythmic: String,
    pub section: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub strains: Option<String>,
    pub favorite: Option<i32>,
    pub kind: Option<String>,
    pub create_time: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub traditional_contents: Option<String>,
    pub dynasty: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
